# frozen_string_literal: true

source 'https://rubygems.org'

gem 'irb', '~> 1.14'
gem 'json', '~> 2.7'
gem 'puma', '~> 6.4'
gem 'rack-unreloader', '~> 2.1', group: :development
gem 'rake'
gem 'roda', '~> 3.88'
gem 'teneo-format_library', path: '/app/gem'

group :development do
  gem 'rack-test', '~> 2.1'
  gem 'rspec', '~> 3.13'
  gem 'rspec-openapi', '~> 0.28'
end
