# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: format_library.proto for package 'Teneo.FormatLibrary.V1'

require 'grpc'
require 'format_library_pb'

module Teneo
  module FormatLibrary
    module V1
      module HealthService
        # Health check service
        class Service

          include ::GRPC::GenericService

          self.marshal_class_method = :encode
          self.unmarshal_class_method = :decode
          self.service_name = 'teneo.format_library.v1.HealthService'

          rpc :Check, ::Teneo::FormatLibrary::V1::HealthCheckRequest, ::Teneo::FormatLibrary::V1::HealthCheckResponse
        end

        Stub = Service.rpc_stub_class
      end
      module FormatService
        # Format service
        class Service

          include ::GRPC::GenericService

          self.marshal_class_method = :encode
          self.unmarshal_class_method = :decode
          self.service_name = 'teneo.format_library.v1.FormatService'

          rpc :ListFormats, ::Teneo::FormatLibrary::V1::ListFormatsRequest, ::Teneo::FormatLibrary::V1::ListFormatsResponse
          rpc :SearchFormats, ::Teneo::FormatLibrary::V1::SearchFormatsRequest, ::Teneo::FormatLibrary::V1::SearchFormatsResponse
          rpc :GetFormat, ::Teneo::FormatLibrary::V1::GetFormatRequest, ::Teneo::FormatLibrary::V1::Format
          rpc :GetFormatRelations, ::Teneo::FormatLibrary::V1::GetFormatRelationsRequest, ::Teneo::FormatLibrary::V1::FormatRelationsResponse
          rpc :GetRelatedFormats, ::Teneo::FormatLibrary::V1::GetRelatedFormatsRequest, ::Teneo::FormatLibrary::V1::RelatedFormatsResponse
          rpc :GetFormatTags, ::Teneo::FormatLibrary::V1::GetFormatTagsRequest, ::Teneo::FormatLibrary::V1::FormatTagsResponse
        end

        Stub = Service.rpc_stub_class
      end
      module TagService
        # Tag service
        class Service

          include ::GRPC::GenericService

          self.marshal_class_method = :encode
          self.unmarshal_class_method = :decode
          self.service_name = 'teneo.format_library.v1.TagService'

          rpc :ListTags, ::Teneo::FormatLibrary::V1::ListTagsRequest, ::Teneo::FormatLibrary::V1::ListTagsResponse
          rpc :GetTag, ::Teneo::FormatLibrary::V1::GetTagRequest, ::Teneo::FormatLibrary::V1::Tag
          rpc :GetTagFormats, ::Teneo::FormatLibrary::V1::GetTagFormatsRequest, ::Teneo::FormatLibrary::V1::ListFormatsResponse
        end

        Stub = Service.rpc_stub_class
      end
    end
  end
end
