name: fl_gem

services:
  build:
    container_name: gem_build
    image: gem_build
    user: "${USER_ID:-1000}:${GROUP_ID:-1000}"
    environment:
      CHANGELOG_GITHUB_TOKEN: ${CHANGELOG_GITHUB_TOKEN}
    networks:
      - db_net
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ..:/app
    restart: no
    profiles:
      - build

  test:
    container_name: gem_test
    image: gem_test
    user: "${USER_ID:-1000}:${GROUP_ID:-1000}"
    environment:
      DB_ADAPTER: postgresql
      DB_HOST: fl_db
      DB_PORT: 5432
      DB_NAME: "${DB_NAME:-teneo}"
      DB_USER: "${DB_USER:-teneo}"
      DB_PASSWORD: "${DB_PASSWORD:-teneo}"
      GEM_VERSION: ${GEM_VERSION:-1.0}
    networks:
      - db_net
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ../seeds:/seeds
      - ./teneo-format_library-${GEM_VERSION}.gem:/app/teneo-format_library-${GEM_VERSION}.gem
    restart: no
    profiles:
      - test

networks:

  db_net:
    external: true
