# frozen_string_literal: true

source 'https://rubygems.org'

# git_source(:github) { |repo| "https://github.com/#{repo}.git" }

# Specify your gem's dependencies in teneo-data_model.gemspec
gemspec

group :development do
  gem 'github_changelog_generator', '~> 1.0', '>= 1.18.0'
  gem 'rubocop', '~> 1.0', '>= 1.74.0'
  gem 'ruby-lsp', '~> 0.0', '>= 0.23.11'
end

group :test do
  gem 'rspec', '~> 3.0', '>=3.13.2'
end
