# frozen_string_literal: true

# Configure the database connection
require 'teneo/format_library'
Teneo::FormatLibrary::Database.config(
  host: ENV['DB_HOST'] || 'localhost',
  port: ENV['DB_PORT']&.to_i || 5432,
  database: ENV['DB_NAME'] || 'teneo',
  user: ENV['DB_USER'] || 'teneo',
  password: ENV['DB_PASSWORD'] || 'teneo',
  adapter: ENV['DB_ADAPTER']&.to_sym || :postgresql
)
Teneo::FormatLibrary::Database.reconnect

# OpenAPI generation configuration
require 'rspec/openapi'

unless ENV['OPENAPI'].nil?

  RSpec::OpenAPI.path =
    if ENV.fetch('OPENAPI_FORMAT', nil) == 'both'
      # Emit both YAML and JSON from a single run by passing an array of paths.
      %w[yaml json].map { |ext| "doc/openapi.#{ext}" }
    else
      "doc/openapi.#{ENV['OPENAPI_FORMAT'] || 'yaml'}"
    end

  RSpec::OpenAPI.title = 'Format Library REST API'
  RSpec::OpenAPI.application_version = Teneo::FormatLibrary::VERSION
  RSpec::OpenAPI.info = {
    description: 'REST API for the Teneo Format Library Service',
    license: {
      name: 'GNU AFFERO GENERAL PUBLIC LICENSE',
      url: 'https://www.gnu.org/licenses/agpl-3.0.en.html'
    }
  }

  RSpec::OpenAPI.servers = ['https://formatservice.teneo.libis.be/library/api/rest/v1']
  RSpec::OpenAPI.comment = <<~END_OF_COMMENT
    This file is auto-generated by rspec-openapi https://github.com/exoego/rspec-openapi

    When you write a spec in spec/requests, running the spec with `OPENAPI=1 rspec` will
    update this file automatically. You can also manually edit this file.
  END_OF_COMMENT
end

# load Rack test methods
require_relative '../app'
require 'rack/test'

RSpec.configure do |config|
  config.include Rack::Test::Methods

  def app
    App
  end
end
