# frozen_string_literal: true

require 'dotenv'
Dotenv.load('.env.local', '.env')

$LOAD_PATH.unshift File.expand_path(File.join(__dir__, '..', '..' ))
require 'teneo/format_library'

path = File.expand_path(__dir__)
Dir.glob(File.join(path, 'tasks', '*.rake')).each { |file| import file }
