# frozen_string_literal: true

source 'https://rubygems.org'

gem 'json', '~> 2.7'
gem 'teneo-format_library', path: '..'

gem 'rack-test', '~> 2.1'
gem 'rspec', '~> 3.13'
gem 'rspec-openapi', '~> 0.28'

gem 'grpc', '~> 1.67'
gem 'grpc-tools', '~> 1.67'

group :development do
  gem 'rake'
end
